services:
  mysql:
    image: mysql:8.0
    container_name: sneakerfever-mysql
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: acceso
    ports:
      - "3308:3306"
    volumes:
      - sneakerfever-mysql-data:/var/lib/mysql

volumes:
  sneakerfever-mysql-data:
